name: Artifacts
run-name: ${{ github.actor }} is learning about artifacts

on:
  push:
    branches: 
        - artifacts

jobs:
  upload_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create an artifact file
        run: echo "This is a sample artifact log file." > test.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log
          retention-days: 1

  download_artifact:
    needs: upload_artifact
    runs-on: ubuntu-latest1

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact

      - name: Cat file
        run: cat test.log