name: Cache
run-name: I'm learning caching

on:
  push:
    branches:
        - cache

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Download repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.13'

            - name: Set up cache 
              uses: actions/cache@v4
              with: 
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: ${{ runner.os }}-pip-

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Test script
              run: python script.py
            