name: Issue is opened 
run-name: Someone has opened an issue!

on: 
  issues:
    types: [created]

jobs: 
  issue_job:
    runs-on: ubuntu-latest

    steps:
      - name: Issue opened
        run: echo "Issue opened successfully"