name: Share Data
run-name: ${{ github.actor }} is learning sharing data between steps

on: 
  push:
    branches:
      - shared_data

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: The GITHUB_OUTPUT file 1
        run: echo $GITHUB_OUTPUT

      - name: Sharing variable in GITHUB_OUTPUT
        id: set_variable_step
        run: echo "my_variable=Hello GitHub Actions" >> $GITHUB_OUTPUT

      - name: Accessing the previous variable with step context outputs, steps.ID_step
        run: |
          echo "My variable is ${{ steps.set_variable_step.outputs.my_variable }}"
          echo "El resultado del anterior step es ${{ steps.set_variable_step.conclusion}}"

      - name: Check outputs
        run: echo "${{ steps.set_variable_step.outputs }}"